# Пользователи
## Создать нового пользователя
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Thomas Muller",
  "email": "thomas@gmail.ru",
  "avatarPath": "photo.png",
  "rank": "Pro",
  "password": "bayern"
}
###

## Авторизовать пользователя
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

# {
#   "email": "kane@gmail.ru",
#   "password": "hurricane"
# }

{
  "email": "thomas@gmail.ru",
  "password": "bayern"
}
###

## Отправить изображение
POST http://localhost:4000/users/653cf0193b0a4a5bce752867/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="clock.jpg"
Content-Type: image/png

< C:\Users\Monika Schultz\Desktop\2440575-six-cities-2\upload\clock.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

## Проверить токен пользователя
GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiSGFycnkgS2FuZSIsImVtYWlsIjoia2FuZUBnbWFpbC5ydSIsImlkIjoiNjU0ODcxZDRlZjI2MTkzZWNkNWYyMGI0IiwiaWF0IjoxNjk5NjE2NjQxLCJleHAiOjE2OTk3ODk0NDF9.KktiVBaHslxks3QMX1U5OKVXdsP50BFxUSN3Dd-cpKU
###
