# Комментарии
## Добавить комментарий к офферу по id оффера
POST http://localhost:4000/comments/654b244c76cbf27214ea7de9 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiVGhvbWFzIE11bGxlciIsImVtYWlsIjoidGhvbWFzQGdtYWlsLnJ1IiwiaWQiOiI2NTRiMWJmNmNhNGQzOGE1ZTcxZDViMGQiLCJpYXQiOjE2OTk0MjM3MTEsImV4cCI6MTY5OTU5NjUxMX0.QSDp2KOb61YtC6ThvuzMwXDHo1b9V7TP51A_QVot9Kg

{
  "text": "ЕЩЕ ОДИН комментарий от Томаса с рейтингом равным 2",
  "rating": 2
}
###

## Получить список комментариев к офферу по id оффера
GET http://localhost:4000/comments/654871a654427e61077adeba HTTP/1.1
###
